- name: Find out if Jboss is installed
  hosts: all
  gather_facts:
  strategy: free
  tasks:
  - name: Find Jboss if installed using PowerShell
    ansible.windows.win_service_info:
      name: WildFly
    register: show_hits

  - name: Show hits variable
    debug:
      msg: "{{ show_hits.services }}"
    when: show_hits.services