- name: Find out if Jboss is installed
  hosts: all
  gather_facts:
  strategy: free
  tasks:
  - name: Look for Jboss service
    ansible.windows.win_service_info:
      name: WildFly
    register: show_hits

  - name: Show hits variable
    debug:
      var: show_hits 
    #when: show_hits.services
#      msg: "{{ show_hits.services }}"
#    when: show_hits.services
